# Generated by Django 2.2.7 on 2019-11-10 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=120)),
                ('correo', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('tipo', models.CharField(max_length=80)),
                ('precio', models.PositiveIntegerField()),
                ('restaurante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reportes.Restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_envio', models.CharField(max_length=120)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Producto')),
                ('restaurante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reportes.Restaurante')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reportes.Usuario')),
            ],
        ),
    ]
