# Generated by Django 2.2.7 on 2019-11-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='ciudad',
            field=models.CharField(default='Ciudad', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('C', 'Comida'), ('B', 'Bebida'), ('P', 'Postre')], max_length=1),
        ),
    ]
