# Generated by Django 2.2.7 on 2019-11-10 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20191110_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='producto',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Restaurante'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='ciudad',
            field=models.CharField(choices=[('BOG', 'Bogota D.C'), ('BGA', 'Bucaramanga'), ('MDE', 'Medellín'), ('CLO', 'Cali')], max_length=3),
        ),
    ]
