# Generated by Django 2.2.7 on 2019-11-12 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0010_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
