# Generated by Django 2.2.7 on 2019-11-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0011_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.ManyToManyField(to='reportes.Producto'),
        ),
        migrations.DeleteModel(
            name='ProductoPedido',
        ),
    ]
