# Generated by Django 2.2.7 on 2019-11-12 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0013_auto_20191111_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reportes.Usuario')),
                ('vehiculo', models.CharField(choices=[('B', 'Bicicleta'), ('M', 'Moto'), ('C', 'Carro')], max_length=1)),
            ],
            bases=('reportes.usuario',),
        ),
    ]
