# Generated by Django 2.2.7 on 2019-11-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0016_auto_20191111_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='https://d1ralsognjng37.cloudfront.net/0a51c720-0283-4c22-87d9-6cd7a484d373.jpeg', upload_to='static/img'),
        ),
    ]
