# Generated by Django 2.2.7 on 2019-11-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0017_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='pedido_asignado',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='reportes.Pedido'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='https://d1ralsognjng37.cloudfront.net/0a51c720-0283-4c22-87d9-6cd7a484d373.jpeg', upload_to='reportes/static/reportes/img'),
        ),
    ]
