# Generated by Django 2.2.7 on 2019-11-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0026_auto_20191114_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamo',
            old_name='estado',
            new_name='resuelto',
        ),
    ]
